### ISSUE TITLE
Stopping the test when no baseline exists prevents all screenshots from being taken

### ISSUE THREAD

**Issue by jbrangwyn** [Visual-Regression-Tracker/agent-cypress#128]
Hi, I'm currently implementing this and have come across an issue.

We have a cypress command that modifies the viewport and takes 5 screenshots at different screen sizes. The issue is that when the first screenshot has no baseline, the test stops and doesn't take the next 4 screenshots. 

Setting enableSoftAssert: true let's the test run all the way through, but then causes another problem - the tests never fail when there are differences.

It would be great to have an auto-approve if no baseline exists setting in VRT, or alternatively a way to take all the screenshots before the test fails. 

Thanks.

**Comment by pashidlos** [comment]
@jbrangwyn thank for request
Usually when I run from my local I enable soft asserts 
For CI it's always false 
This way when I make new test first I run them locally

Also, making the test parameterized instead of loop as such would not fail the rest cases if one failed
