### ISSUE TITLE
How does vrtTrackBase64 command work?

### ISSUE THREAD

**Issue by alexniculae** [Visual-Regression-Tracker/agent-cypress#172]
I see that the vrtTrackBase64 command requires an image to be added as an argument for execution.

Could you please share some example of how this function can be used?
I found an example here: https://github.com/Visual-Regression-Tracker/examples-js/blob/17575d8621e4974b24b462a009250a281d79616e/agent-cypress/cypress/integration/vrt.spec.js#L18

But is the tool restricted to using an image that exists locally, or can it take as an argument the cy.screenshot command?

Would be interesting to better understand how that works 🙂 

Also, maybe it'd be interesting for admin to open up a `Discussions` section in the VRT Gitlab projects, where we can ask such questions and discuss topics with project administrators and the community.

**Comment by pashidlos** [comment]
@alexniculae for `vrtTrackBase64` it's required to pass image as base64 string like when you reed it from fixtures folder 
it could be used also via some services that makes screenshot on server side and returns response in `base64`

you can't use it with `cy.screenshot ` as this command does not yeld image as result
so default `vrtTrack` could be used 

feel free to start any discussions here https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/discussions
