### ISSUE TITLE
cannot use VRT + Cypress agent to compare images for projects that use odiff or look-same libraries

### ISSUE THREAD

**Issue by alexniculae** [Visual-Regression-Tracker/agent-cypress#175]
Trying to use VRT + Cypress agent to compare images for projects that use `odiff` or `look-same` image compare libraries will result in the following error:

```
  CypressError: `cy.task('VRT_TRACK_IMAGE_MULTIPART')` failed with the following error:

  > {
        "path": "/test-runs/multipart",
        "name": "Error",
        "message": "",
        "exception": {},
        "stack": "Error\n    at ChildProcess.<anonymous> (/node_modules/odiff-bin/odiff.js:147:13)\n    at ChildProcess.emit (events.js:327:22)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:315:20)\n    at Pipe.<anonymous> (net.js:674:12)"
  }

  https://on.cypress.io/api/task
```

Could you please let me know if
- this might come from something that I am not doing correctly
  - e.g. an error in the installation or the implementation, or
- if it's an expected/known issue
  - e.g. cannot use odiff or look-same libraries with Cypress agent

I tried to find some documentation on this or troubleshoot myself, but unfortunately could not find anything.

Thank you 🙂

**Comment by alexniculae** [comment]
After some more investigations it looks like:
- only projects that use `odiff` library for the comparison are failing with the above error
- they don't fail when creating the baseline image, only when trying to check the diffs
- any new print-screen seems to be created in the VRT project build as a new baseline, with status New
  - maybe because the diffs are never calculated by the `odiff` library

If I can share more details on this, I'd be happy to. Not sure if anyone else has faced this problem in the past or is now.

**Comment by pashidlos** [comment]
thanks for your question 

unfortunately there is en issue using `odiff` library inside `alpine` linux  docker images https://github.com/dmtrKovalenko/odiff/issues/55

unless it's solved or any known workaround found we could not utilise that

**Comment by alexniculae** [comment]
Thank you Pavel, good to know this 🙂 

Closing this issue then, as it will be fixed in the thread above.
