### ISSUE TITLE
error adding commands from documentation

### ISSUE THREAD

**Issue by victorxavieratlas** [Visual-Regression-Tracker/agent-cypress#217]
I'm using the latest version of VRT Agent Cypress.
After adding the command settings from the documentation, I get this error when running the tests.

### Error
![image](https://user-images.githubusercontent.com/90327179/214065130-03f16afb-d8be-4d36-b0c6-4e8a21c5d98d.png)

### support/commands.js
![image](https://user-images.githubusercontent.com/90327179/214065875-ab8927d5-4114-4d42-abce-caa720479fca.png)

**Comment by pashidlos** [comment]
@victorxavieratlas what cypress version are you using?
could you reproduce the issue with code from examples?
https://github.com/Visual-Regression-Tracker/examples-js/tree/master/agent-cypress

**Comment by victorxavieratlas** [comment]
@pashidlos cypress version 12.3.0
Between today and tomorrow I will have time to try to reproduce the error in the example code :)

**Comment by pashidlos** [comment]
@victorxavieratlas I'm using version 10, seems to be version compatibility changes 
need to migrate code to newest version

**Comment by paazmaya** [comment]
Migration work has started in #238

**Comment by paazmaya** [comment]
@victorxavieratlas please try with https://github.com/Visual-Regression-Tracker/agent-cypress/releases/tag/v5.7.0 which has upgraded to Cypress 12
