### ISSUE TITLE
Request for updated plugin example for cypress 10+

### ISSUE THREAD

**Issue by azz0r** [Visual-Regression-Tracker/agent-cypress#239]
Hello,

The plugin interface has changed on Cypress; I appreciate any example or update in the documentation on maintaining the integration.

 - Thanks

**Comment by pashidlos** [comment]
@azz0r thanks for feedback 
the documentation hast to be up to date 
the examples are also updated https://github.com/Visual-Regression-Tracker/examples-js
could you elaborate on what is not working?

**Comment by azz0r** [comment]
Hey the updated documentation you've linked to helped, specifically this commit: https://github.com/Visual-Regression-Tracker/examples-js/commit/87af77082be1afa3d01027302cb2dce7fcd4915f

Appreciated. Love the work you guys do on this tool also, it's a lifesaver at work :)
