### ISSUE TITLE
How to disable this in local environment?

### ISSUE THREAD

**Issue by beshur** [Visual-Regression-Tracker/agent-cypress#263]
Hi!

We use this plugin on our CI to make use of the tests and keep the library updated.

But on local env the tests don't run without this plugin configured (and we don't want to configure it locally).
Is there a workaround?

**Comment by pashidlos** [comment]
not sure why don't you want to configure [local config](https://github.com/Visual-Regression-Tracker/agent-cypress#or-as-json-config-file-vrtjson) 
if there is no configuration for vrt than exclude it from test suite

**Comment by beshur** [comment]
I tried to insert dummy values into local config, but it breaks as well since there is no VRT server at that dummy location.

**Comment by beshur** [comment]
The problem is that some of our tests are explicitly updated with `cy.vrtTrack` and other things, and I want to keep it that way.

**Comment by pashidlos** [comment]
there is nothing like that in lib

**Comment by beshur** [comment]
maybe there is a test utility - like a mock of all the library that can be assigned to `cy` under certain conditions?

**Comment by pashidlos** [comment]
@beshur there are two point integration by adding
- plugin in config
- test step

there is no configuration to mock whole library on configuration 
you could wrap it in custom code to do that

**Comment by beshur** [comment]
Thanks!
I did it like this https://gist.github.com/beshur/c2c384e9572253f63049a8de4db2b0a3
