### ISSUE TITLE
Getting error while executing VRT command for long page (Need a lot scrolling)

### ISSUE THREAD

**Issue by maulik190** [Visual-Regression-Tracker/agent-cypress#75]
VRT server is running. Here, is my code. 

```
    cy.visit("https://en.wikipedia.org/wiki/United_States");
    cy.vrtTrack(`tos-Test2` , {diffTollerancePercent: 3});
```

<img width="223" alt="Error" src="https://user-images.githubusercontent.com/13773749/108775995-cc834600-752f-11eb-8af0-1cc3ba3d821f.PNG">

Would you please provide any suggestion to fix the error?

**Comment by pashidlos** [comment]
@maulik190 thanks for your request 
could you add more details regarding specific versions you are using for cypress and agent-cypress libs?
as I'm getting different error: `cy.screenshot() timed out waiting 30000ms to complete.` 
despite changing timeout it still refuse to take image successfully

the error you are getting there is when VRT service is unreachable and I could not reproduce this using your steps 
seem something happened with service after build was successfully started

**Comment by pashidlos** [comment]
this code is failing for me running with `cypress open` but works fine with `cypress run` and seems to be cypress issue 
```
    cy.visit("https://en.wikipedia.org/wiki/United_States");
    cy.screenshot("big-image", { timeout: 100000 });
```

**Comment by maulik190** [comment]
Below code is still not working with cypress run. I tried to restart VRT server, still not capturing image successfully.

```
cy.visit("https://en.wikipedia.org/wiki/United_States");
cy.vrtTrack(`big-image` , { timeout: 100000 }); 
```
Cypress Version: 6.1.0   
How to check version of agent-cypress libs?

**Comment by pashidlos** [comment]
@maulik190 what error you are getting?
does it works for other images?
check logs from `docker-compose` if there any errors
